challenge = reto1 reto2 reto3 reto4 reto5

all: $(challenge)

reto1: challenge1.c
	gcc -o $@ $<
reto2: challenge2.c
	gcc -o $@ $<
reto3: challenge3.c
	gcc -o $@ $<
reto4: challenge4.c
	gcc -o $@ $<
reto5: challenge5.c
	gcc -o $@ $<

clean: rm -f $(challenge)
